[package]
name = "web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
askama = "0.16.1"
axum = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
domain = { path = "../domain" }
serde = { version = "1", features = ["derive"] }
tower-http = { version = "0.6", features = ["fs"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
